### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by yathit** [delightfulgoods/flutter_payments#4]
```
The target “flutter_payments” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.
```

**Comment by pplante** [comment]
I'm using swift 4.  Not sure why you're seeing that error.  Is xcode up to date?

**Comment by yathit** [comment]
I think my flutter project was created long time ago without swift support. And there is [3.2 --> 4.0 issue](https://stackoverflow.com/questions/46338588/xcode-9-swift-language-version-swift-version). Adding `SWIFT_VERION` does not work. Also do not know how to convert. Still figuring out.

**Comment by pplante** [comment]
You can generate a new project and then copy the iOS folder over, unless you have a lot of customization to the iOS code.

**Comment by yathit** [comment]
Thanks. After refresh by creating a new project, all works fine. In fact, I am glad to do that. It seems a lot different from alpha template that I were using. For one, there is automatic version string addition. It does save time.

**Comment by RobertBrunhage** [comment]
@pplante Sorry to comment on a closed thread but tested now on my IOS and go the same problem. The thing is that I have already created a new project but still got this issue :/

**Comment by RobertBrunhage** [comment]
Got this issue when adding support in the podfile:
from this example: https://github.com/flutter/flutter/issues/16049 I added:
    config.build_settings['SWIFT_VERSION'] = '3.2'

But then I got this issue

/Users/robertbrunhage/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_payments-0.1.5/ios/Classes/FlutterPaymentsPlugin.m:2:9: fatal error: 'flutter_payments/flutter_payments-Swift.h' file not found
    #import <flutter_payments/flutter_payments-Swift.h>

**Comment by RobertBrunhage** [comment]
Saw that when creating a new project for IOS objective-C is pre-selected for my projects and not swift. Does that make any difference?

**Comment by RobertBrunhage** [comment]
Followed the last answer on this: https://github.com/firstfloorsoftware/flutter_sodium/issues/1 which fixed the issue
